import type { PaymentSplit } from "../lib/paymentModes";

/** View model for the printable service invoice shell (Quick bill, SRF service bill, etc.). */
export type ServiceInvoiceLineView = {
  slNo: number;
  spareCode?: string | null;
  description: string;
  hsnSac: string;
  /** Unit price (taxable), before quantity */
  unitPrice: number;
  qty: number;
  /** Line taxable (gross) = unitPrice * qty */
  grossValue: number;
};

export type ServiceInvoiceTaxRow = {
  description: string;
  taxable: number;
  cgst: number;
  sgst: number;
  total: number;
};

export type ServiceInvoiceViewModel = {
  documentLabel: string;
  /** Shown on layout e.g. "Quick Bill" / "Service bill" */
  invoiceType?: string;
  /** Service ref / SR no. (SRF ref or secondary id) */
  serviceReference?: string | null;
  invoiceNumber: string;
  invoiceDate: string;
  placeOfSupply: string;
  reverseCharge: string;
  seller: {
    legalName: string;
    addressLines: string[];
    gstin: string;
    phone?: string;
    email?: string;
    stateCode?: string;
  };
  /** e.g. "SINCE 1948" under logo area */
  sellerTagline?: string;
  billTo: {
    name: string;
    address?: string | null;
    gstin?: string | null;
    pan?: string | null;
    phone?: string | null;
    email?: string | null;
    customerCode?: string | null;
  };
  /** Watch, technician, payment, etc. (legacy meta list — prefer productBlock when set) */
  serviceMeta: { label: string; value: string }[];
  /** Structured product / repair block for invoice table header area */
  productBlock?: {
    brandName: string;
    brandModel: string;
    modelOrSerial: string;
    natureOfRepair: string;
  };
  lines: ServiceInvoiceLineView[];
  totalAmount: number;
  /** Deprecated: use amountInWords */
  amountInWordsNote?: string;
  amountInWords?: string;
  paymentMode?: string;
  /** Split payments (Cash + UPI, etc.) when present. */
  paymentSplits?: PaymentSplit[];
  bankDetailsLines?: string[];
  notes?: string;
  footerTerms?: string[];
  /** Totals section */
  grossTaxableTotal?: number;
  totalCgst?: number;
  totalSgst?: number;
  totalTax?: number;
  netPayable?: number;
  totalQty?: number;
  advanceAmount?: number;
  amountPaid?: number;
  paymentRemarks?: string;
  taxBreakdownRows?: ServiceInvoiceTaxRow[];
  /** App user id or label for "Invoice generated by" */
  generatedBy?: string | null;
  /** "For ZIMSON TIMES PVT LTD" style footer */
  invoiceLegalFooter?: string;
  /** Logo URL from settings (optional) */
  sellerLogoUrl?: string | null;
};
